name: Painter
version: ${project.version}
main: dev.pace.painter.Painter
api-version: 1.8.8
commands:
  Paint:
    description: Paint command.
  Painting:
    description: Painting alternative command.