name: Painter
version: 0.4
main: dev.pace.painter.Painter
api-version: 1.16
commands:
  Paint:
    description: Paint command.
  Painter:
    description: Painting alternative command.
  painthelp:
    description: Shows all commands and help for the plugin.
    aliases:
      - painterhelp